## Learning Numpy. The Hard Way. 

Вам нужно выполнить упражнения по Numpy.


#### Задание 1.
```python
 # Q. Import numpy as np and print the version number.
```

In [1]:
import numpy as np

#### Задание 2.
```python
# Q. Create a 1D array of numbers from 0 to 9

# Desired Output
# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [5]:
a = np.array(np.arange(10))
print(a)
print(a[9])

[0 1 2 3 4 5 6 7 8 9]
9


#### Задание 3.
```python
 # Q. Create a 3×3 numpy array of all True’s
```

In [12]:
b = np.ones((3,3))
c = (b > 0)

print(c)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### Задание 4.
```python
# Q. Extract all odd numbers from arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# > array([1, 3, 5, 7, 9])
```

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_elem = arr[arr % 2 != 0]

print(odd_elem)

[1 3 5 7 9]


#### Задание 5.
```python
# Q. Replace all odd numbers in arr with -1
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [17]:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Задание 6.
```python
# Q. Replace all odd numbers in arr with -1 without changing arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# out #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
copy_arr = np.copy(arr)
copy_arr[copy_arr % 2 != 0] = -1

print(arr)
print(copy_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Задание 7.
```python
# Q. Convert a 1D array to a 2D array with 2 rows
# Input 
arr = np.arange(10)
print("Input")
arr

# Desired Output
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])
```

In [26]:
arr = np.arange(10)
convert = np.reshape(arr, (2, -1))
print(convert)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Задание 8.
```python
# Q. Stack arrays a and b vertically
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a
b

# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```
https://habr.com/ru/articles/469355/#p45

In [34]:
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

vert_concat = np.concatenate((a, b), 0)

print(vert_concat)

Input
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Задание 9.
```python
# Q. Stack the arrays a and b horizontally.
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Desired Output
# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [35]:
horizont = np.concatenate((a, b), 1)
print(horizont)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Задание 10.
```python
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input
print("Input")
a = np.array([1,2,3])
a

# Desired Output
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```


In [48]:
a = np.array([1,2,3])

# Repeat each element of a three times
part1 = np.repeat(a, 3)


part2 = np.tile(a, 3)


sum_arr = np.concatenate((part1, part2))

print(sum_arr)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#### Задание 11.
```python
# Q. Get the common items between a and b

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# array([2, 4])
```

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

# Находим пересечение
common_elements = np.intersect1d(a, b)
print(common_elements)

# Если нужно сохранить порядок, как в первом списке используем isin

com_el = a[np.isin(a, b)]
print(com_el)

[2 4]
[2 2 4 4]


#### Задание 12.
```python
# Q. From array a remove all items present in array b

# Input
print("Input")
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a
b

# Desired Output
# array([1,2,3,4])
```

In [55]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

rm_arr = a[~np.isin(a, b)] # ~ логическое НЕ 
print(rm_arr)

[1 2 3 4]


#### Задание 13.
```python
# Q. Get the positions where elements of a and b match

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# > (array([1, 3, 5, 7]),)
```

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = np.where((a == b))
print(matching_positions)

(array([1, 3, 5, 7]),)


#### Задание 14.
```python
# Q. Get all items between 5 and 10 from a.

# Input
print("Input")
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

# Desired Output
# (array([6, 9, 10]),)
```

In [63]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

res = a[(a >= 5) & (a <= 10)]
print(res)

[ 6  9 10]


#### Задание 15.
```python
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input

def maxx(x, y):
    """
    Get the maximum of two items
    """
    
    if x >= y:
        return x
    else:
        return y
print("Result of the maxx function")
maxx(1, 5)

print("Input")
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
a
b

# Desired Output
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [65]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = np.maximum(a, b)

print(result)

[6 7 9 8 9 7 5]


#### Задание 16.
```python
# Q. Swap columns 1 and 2 in the array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [69]:
arr = np.arange(9).reshape(3,3) 
print(arr)
arr[:, [0,1]] = arr[:, [1, 0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Задание 17.
```python
# Q. Swap rows 1 and 2 in the array arr:

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [73]:
arr = np.arange(9).reshape(3,3)
arr[[1, 2], :] = arr[[2, 1], :]
print(arr)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


#### Задание 18.
```python
# Q. Reverse the rows of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [74]:
arr = np.arange(9).reshape(3,3)

reversed = arr[::-1]
print(reversed)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### Задание 19.
```python
# Q. Reverse the columns of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [78]:
arr = np.arange(9).reshape(3,3)
print(arr)
reversed = arr[:, ::-1]
print(reversed)

b = np.array([10, 20, 30, 40, 50])
every_second = b[::2]  # Извлекает каждый второй элемент


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


#### Задание 20.
```python
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
```

In [81]:
# устанавливаем диапазон значений 
low = 5
high = 10

random_arr = np.random.uniform(low, high, size = (5, 3))

print(random_arr)

[[9.0910329  6.73469733 7.52490652]
 [7.41968657 9.7990687  6.10334208]
 [5.27282785 5.56680574 9.35349497]
 [6.63096016 6.6361194  9.4769313 ]
 [9.3348272  9.56165579 5.16308176]]
