## Learning Numpy. The Hard Way. Part 2.

Вам нужно выполнить следующую часть упражнений по Numpy.


#### Задание 21.
```python
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
```

In [2]:
import numpy as np

In [6]:
# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=3, suppress=False, threshold=1000, formatter=None)

# Input precision=8
print("Input")
rand_arr = np.random.random((5,3))
rand_arr

Input


array([[0.873, 0.145, 0.792],
       [0.676, 0.883, 0.762],
       [0.037, 0.8  , 0.163],
       [0.805, 0.529, 0.186],
       [0.554, 0.688, 0.255]])

#### Задание 23.
```python
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.



# Desired Output
# > array([ 0,  1,  2, ..., 12, 13, 14])
```

In [12]:
# Setting print options to default
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=6, formatter=None)

# Input  threshold=6 
print("Input")
a = np.arange(15)
a

Input


array([ 0,  1,  2, ..., 12, 13, 14])

In [9]:
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=True, threshold=1000, formatter=None)

# Input   suppress=True
print("Input")
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

Input


array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

#### Задание 24.
```python
# Q. Print the full numpy array a without truncating.


# Desired Output
# > array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

In [14]:

# Input
print("Input")
np.set_printoptions(threshold=np.inf)
a = np.arange(15)
a

Input


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Задание 25.
```python
# Q. Import the iris dataset keeping the text intact.

# Input
# Use the iris dataset provided
print_files()

# All the available options of the numpy genfromtxt function
# numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, 
#                    skip_footer=0, converters=None, missing_values=None, filling_values=None, 
#                    usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\]^{|}~", 
#                    replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', 
#                    unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')[source]
```

#### Задание 26.
```python
# Q. Extract the text column species from the 1D iris imported in previous question.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 27.
```python
# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 28.
```python
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 29.
```python
# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 30.
```python
# Q. Compute the softmax score of sepallength.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 31.
```python
# Q. Find the 5th and 95th percentile of iris's sepallength

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 32.
```python
# Q. Insert np.nan values at 20 random positions in iris_2d dataset

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

#### Задание 33.
```python
#### Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

#### Задание 34.
```python
# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

#### Задание 35.
```python
# Q. Select the rows of iris_2d that does not have any nan value.

# Input
# Use the titanic dataset provided
print_files()

# set original print statements
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)
```

#### Задание 36.
```python
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

#### Задание 37.
```python
# Q. Find out if iris_2d has any missing values.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

#### Задание 38.
```python
# Q. Replace all ccurrences of nan with 0 in numpy array

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

#### Задание 39.
```python
# Q. Find the unique values and the count of unique values in iris's species

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

#### Задание 40.
```python
# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```